### PR TITLE
Show group in task

### PR DESCRIPTION
**Pull request by lauraGit**
My aim is to know the group in order to fetch "/groups/{groupId}" in task to get group members for the select to change assignee. I guess in the future we can include the group name to build the breadcrumb. Other option would be to create a new enpoint similar to "/tasks/{taskId}/possibleAssignees" or a new property in Task with "possibleAssignees".

I had problems again with the recursive serialization. I tested another approached different than before with the EntityLevelView.CompleteCourse.class and EntityLevelView.CourseYearComplete.class as here I need two levels up in the hierarchy. Solution is inspired by this article: https://www.baeldung.com/jackson-call-default-serializer-from-custom-serializer . I access the ObjectMapper with a cast, which isn't nice but works.

### CODE REVIEW

**Comment by neich** [comment]
To deal with infinite recursion when serializing to JSON, you can use JsonIdentityInfo: https://www.baeldung.com/jackson-bidirectional-relationships-and-infinite-recursion

The problem is to find a client library in JS that handles the format

**Comment by neich** [comment]
Maybe this ?

https://itnext.io/jackson-js-powerful-javascript-decorators-to-serialize-deserialize-objects-into-json-and-vice-df952454cf

**Comment by lauraGit** [comment]
This can be interesting to use in tasks or history of tasks where we can reduce response size and have something like:
```
{ "name": "Lorem ipsum", "assignee": { "username": "john.doe", "avatar": "https://...." }},
{ "name": "Lorem ipsum", "assignee":  "john.doe" }
```
I removed the JsonIdentityInfo from user because I had a json like this (with ids, instead of usernames) in the groups list. With this it could be possible to re-add again.

**Comment by neich** [comment]
I think this would simplify very much the infinite recursion issue

**Pull request merged**
